# Site settings
title: Richard Yhip's Brain Matter
email: richard.yhip@gmail.com
description: I primarily post musings about software development and technology here. Hopefully someone will find the things I say on here useful one day!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yhippa.github.io" # the base hostname & protocol for your site
twitter_username: Yhippa
github_username: yhippa

# Build settings
markdown: kramdown
